"""initial schema

Revision ID: 70442d5004e0
Revises: 
Create Date: 2026-07-06 10:48:33.645078
"""
from __future__ import annotations

import aios_storage.models
import sqlalchemy as sa
from alembic import op

revision = '70442d5004e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # teacher_vectors.vector は PostgreSQL では pgvector の vector 型になるため
    # 事前に拡張を有効化する(SQLite など他方言では不要のためスキップ)。
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_cycles',
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('step_no', sa.BigInteger(), nullable=False),
    sa.Column('tv_id', sa.String(length=36), nullable=True),
    sa.Column('dissipation', sa.Float(), nullable=True),
    sa.Column('dissipation_algo', sa.String(length=40), nullable=False),
    sa.Column('health', sa.String(length=10), nullable=False),
    sa.Column('lr_correction', sa.Float(), nullable=False),
    sa.Column('noise_amount', sa.Float(), nullable=False),
    sa.Column('fitness_mean', sa.Float(), nullable=True),
    sa.Column('rehatch_count', sa.Integer(), nullable=False),
    sa.Column('probe_missing', sa.Integer(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cycle_id'),
    sa.UniqueConstraint('cohort_id', 'step_no')
    )
    op.create_index(op.f('ix_cohort_cycles_cohort_id'), 'cohort_cycles', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_cycles_measured_at'), 'cohort_cycles', ['measured_at'], unique=False)
    op.create_table('cohorts',
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('tv_dimension', sa.Integer(), nullable=False),
    sa.Column('ema_alpha', sa.Float(), nullable=False),
    sa.Column('loop_state', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cohort_id')
    )
    op.create_index(op.f('ix_cohorts_tenant_id'), 'cohorts', ['tenant_id'], unique=False)
    op.create_table('knowledge_archives',
    sa.Column('archive_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('source_slot_id', sa.String(length=36), nullable=True),
    sa.Column('source_generation', sa.Integer(), nullable=True),
    sa.Column('tv_id', sa.String(length=36), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('params_uri', sa.Text(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('distill_allowed', sa.Boolean(), nullable=False),
    sa.Column('storage_tier', sa.String(length=10), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('archive_id')
    )
    op.create_index(op.f('ix_knowledge_archives_archived_at'), 'knowledge_archives', ['archived_at'], unique=False)
    op.create_index(op.f('ix_knowledge_archives_cohort_id'), 'knowledge_archives', ['cohort_id'], unique=False)
    op.create_table('model_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('adapter_kind', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('params_uri', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('slot_id', 'generation')
    )
    op.create_index(op.f('ix_model_snapshots_slot_id'), 'model_snapshots', ['slot_id'], unique=False)
    op.create_table('task_records',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('task_metadata', sa.JSON(), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('tv_id', sa.String(length=36), nullable=True),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('routing_reason', sa.JSON(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('cohort_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_task_records_cohort_id'), 'task_records', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_task_records_requested_at'), 'task_records', ['requested_at'], unique=False)
    op.create_index(op.f('ix_task_records_slot_id'), 'task_records', ['slot_id'], unique=False)
    op.create_index(op.f('ix_task_records_tenant_id'), 'task_records', ['tenant_id'], unique=False)
    op.create_table('teacher_vectors',
    sa.Column('tv_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('vector', aios_storage.models.VectorColumn(), nullable=False),
    sa.Column('nl_directive', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tv_id')
    )
    op.create_index(op.f('ix_teacher_vectors_cohort_id'), 'teacher_vectors', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_teacher_vectors_measured_at'), 'teacher_vectors', ['measured_at'], unique=False)
    op.create_table('slots',
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('display_id', sa.String(length=10), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('adapter_kind', sa.String(length=50), nullable=False),
    sa.Column('current_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rehatch_lock', sa.Boolean(), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('maturity', sa.BigInteger(), nullable=False),
    sa.Column('fitness', sa.Float(), nullable=True),
    sa.Column('last_rehatch_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('slot_id'),
    sa.UniqueConstraint('cohort_id', 'display_id')
    )
    op.create_index(op.f('ix_slots_cohort_id'), 'slots', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_slots_tenant_id'), 'slots', ['tenant_id'], unique=False)
    op.create_table('slot_events',
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_slot_events_cohort_id'), 'slot_events', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_slot_events_occurred_at'), 'slot_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_slot_events_slot_id'), 'slot_events', ['slot_id'], unique=False)
    op.create_index(op.f('ix_slot_events_tenant_id'), 'slot_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_events_tenant_id'), table_name='slot_events')
    op.drop_index(op.f('ix_slot_events_slot_id'), table_name='slot_events')
    op.drop_index(op.f('ix_slot_events_occurred_at'), table_name='slot_events')
    op.drop_index(op.f('ix_slot_events_cohort_id'), table_name='slot_events')
    op.drop_table('slot_events')
    op.drop_index(op.f('ix_slots_tenant_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_cohort_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_teacher_vectors_measured_at'), table_name='teacher_vectors')
    op.drop_index(op.f('ix_teacher_vectors_cohort_id'), table_name='teacher_vectors')
    op.drop_table('teacher_vectors')
    op.drop_index(op.f('ix_task_records_tenant_id'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_slot_id'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_requested_at'), table_name='task_records')
    op.drop_index(op.f('ix_task_records_cohort_id'), table_name='task_records')
    op.drop_table('task_records')
    op.drop_index(op.f('ix_model_snapshots_slot_id'), table_name='model_snapshots')
    op.drop_table('model_snapshots')
    op.drop_index(op.f('ix_knowledge_archives_cohort_id'), table_name='knowledge_archives')
    op.drop_index(op.f('ix_knowledge_archives_archived_at'), table_name='knowledge_archives')
    op.drop_table('knowledge_archives')
    op.drop_index(op.f('ix_cohorts_tenant_id'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_cohort_cycles_measured_at'), table_name='cohort_cycles')
    op.drop_index(op.f('ix_cohort_cycles_cohort_id'), table_name='cohort_cycles')
    op.drop_table('cohort_cycles')
    # ### end Alembic commands ###
